### ISSUE TITLE
Why don't you add the additional branch (β^2) to the MLP in Eq2?

### ISSUE THREAD

**Issue by zjwzcx** [LeapLabTHU/ActiveNeRF#1]
@Panxuran 
Hi Xuran, thanks for your awesome work!

In Sec 4, you mentioned 'Following previous researches in Bayesian neural networks, we take the model output as the mean'. However, the model outputs the uncertainty/variance _**β^2(r)**_ in a shallower layer, which is even not related to the input _**d**_. It seems more intuitive to have the mean **_c(r, d)_** and variance _**β^2(r)**_ both depend on the same input _**r(t)**_ and _**d**_ (just like the following figure, ref to [NeurAR](https://arxiv.org/abs/2207.10985)). Have you conducted any related experiments or had any insight? 

Look forward to your reply!

**Comment by zjwzcx** [comment]
![2022-10-06_14-28](https://user-images.githubusercontent.com/43678835/194232969-57e20b3f-eb82-4305-91c7-71f4b4b8bf9a.png)

**Comment by Panxuran** [comment]
In our case, we see the uncertainty estimation as an attribute similar to volume density, thus we omit the influence of viewing direction. Also, this assumption helps us to meet the demand of one of the prerequisites, i.e., the independence of radiance value distribution between different positions.

Nevertheless, from my personal opinion, this remains a open question. Modeling uncertainty with viewing direction may be a promising direction. Hope to see your positive results on trying this!
