### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by derrick-xwp** [LeapLabTHU/ActiveNeRF#2]
hi , when will the code be released?

**Comment by jiadingfang** [comment]
Second this, an estimate of the timeline would also be appreciated!

**Comment by zjwzcx** [comment]
Could the auther share the progress of code release? Thanks!
It's frustrating that the author did not reply to my issue and email proposed/sent two months ago :(

**Comment by zjwzcx** [comment]
Has anyone received the reply from the author? My email and github issue haven't been replied since Oct, 2022 :(

**Comment by csrqli** [comment]
Still looking forward to the code!

**Comment by Panxuran** [comment]
Sorry for the inconvenience of the late reply, and we have now released the code. I will now close this issue and feel free to open another one if new problems pop out.
